#!/bin/zsh
#autoload
# Format partition during install process
# Authors:
#   JB
#

function partition_format {

    printf "$fg[yellow]Format partition $1 to $2: $reset_color\n\n"
    case $2 in
        "fat")
            ## mkfs.vfat -F32 -n EFI /dev/sda1
            mkfs.vfat -F32 -n $3 $1 2>&1
            #mkfs.fat -F32 $1
            #printf "$fg[green]Partition $1 formated to $2 $reset_color\n\n"
        ;;
        "btrfs")
            ## mkfs.btrfs -L ROOT /dev/sda2
            mkfs.btrfs -L $3 -f $1 2>&1
            #mkfs.btrfs -f $1
            #printf "$fg[green]Partition $1 formated to $2 $reset_color\n\n"
        ;;
        ($'ext'*)
            ## Force output to stdout else mke2fs generates an error on init for no reason
            mkfs.$2 -L $3 -F $1 2>&1
            #printf "$fg[green]Partition $1 formated to $2 $reset_color\n\n"
        ;;
        *)
            printf "$fg[red]Invalid partion format: $2 requested for: $1 $reset_color\n\n" >&2
        ;;
    esac
    printf "$fg[green]Partition $1 formated to $2 $reset_color\n\n"
}

partition_format "$@"
